### ISSUE TITLE
Audio and video of clip not linked- Export to resolve

### ISSUE THREAD

**Issue by lijovklm** [WyattBlue/auto-editor#188]
Auto-Editor version 21w19a

While using exporting to resolve and imported into resolve cuts are made properly. But the audio and video clips of same cut are not linked. I know this used to work in versions from end of 2020. I recently updated to this version and my cuts are no longer linked.

![image](https://user-images.githubusercontent.com/24433342/121784349-2e47e880-cbd1-11eb-91dc-440563c4d8d7.png)

ideally here both audio and video of same cut should have selected when clicked. Instead, only video clip is selected here.

Command I am using: 
auto-editor VID_20210610_163151.mp4 --frame_margin 12 --min_clip_length 15 --silent_speed 150% -exr

--debug output

   - Temp Directory: C:\Users\ljose3\AppData\Local\Temp\tmp50f4hyy1

Auto-Editor is out of date. Run:

    pip3 install -U auto-editor

to upgrade to the latest version.

Warning! exportMediaOps options are not used when exporting  as an XML.
VID_20210610_163151.mp4Resolve XML file.
   - Speeds: [1.5, 1.0]
   - INPUT_FILE: VID_20210610_163151.mp4
   - newOutput: VID_20210610_163151.xml
  Removing already existing file: VID_20210610_163151.xml
['C:\\Users\\ljose3\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\site-packages\\auto_editor\\win-ffmpeg\\bin\\ffprobe.exe', '-v', 'error', '-select_streams', 'a:0', '-show_entries', 'stream=sample_rate', '-of', 'compact=p=0:nk=1', 'VID_20210610_163151.mp4']
48000

   - sampleRate: 48000
   - audioBitrate: unset
['C:\\Users\\ljose3\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\site-packages\\auto_editor\\win-ffmpeg\\bin\\ffprobe.exe', '-v', 'error', '-select_streams', 'v', '-show_entries', 'stream=avg_frame_rate', '-of', 'compact=p=0:nk=1', 'VID_20210610_163151.mp4']
274760000/9239651

['C:\\Users\\ljose3\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\site-packages\\auto_editor\\win-ffmpeg\\bin\\ffprobe.exe', '-v', 'error', '-select_streams', 'a', '-show_entries', 'stream=index', '-of', 'compact=p=0:nk=1', 'VID_20210610_163151.mp4']
1

['C:\\Users\\ljose3\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\site-packages\\auto_editor\\win-ffmpeg\\bin\\ffmpeg.exe', '-y', '-i', 'VID_20210610_163151.mp4', '-hide_banner', '-map', '0:a:0', '-ac', '2', '-ar', '48000', 'C:\\Users\\ljose3\\AppData\\Local\\Temp\\tmp50f4hyy1\\0.wav', '-map', '0:v:0', '-vf', 'vfrdet', '-f', 'null', '-']
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'VID_20210610_163151.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2021-06-10T11:17:18.000000Z
    com.android.version: 10
  Duration: 00:15:24.00, start: 0.000000, bitrate: 20102 kb/s
    Stream #0:0(eng): Video: h264 (Baseline) (avc1 / 0x31637661), yuvj420p(pc, bt470bg/bt470bg/smpte170m), 1920x1080, 20000 kb/s, SAR 1:1 DAR 16:9, 29.74 fps, 120 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2021-06-10T11:17:18.000000Z
      handler_name    : VideoHandle
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 96 kb/s (default)
    Metadata:
      creation_time   : 2021-06-10T11:17:18.000000Z
      handler_name    : SoundHandle
Stream mapping:
  Stream #0:1 -> #0:0 (aac (native) -> pcm_s16le (native))
  Stream #0:0 -> #1:0 (h264 (native) -> wrapped_avframe (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'C:\Users\ljose3\AppData\Local\Temp\tmp50f4hyy1\0.wav':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    com.android.version: 10
    ISFT            : Lavf58.45.100
    Stream #0:0(eng): Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      creation_time   : 2021-06-10T11:17:18.000000Z
      handler_name    : SoundHandle
      encoder         : Lavc58.91.100 pcm_s16le
Output #1, null, to 'pipe:':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    com.android.version: 10
    encoder         : Lavf58.45.100
    Stream #1:0(eng): Video: wrapped_avframe, yuvj420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 120 fps, 120 tbn, 120 tbc (default)
    Metadata:
      creation_time   : 2021-06-10T11:17:18.000000Z
      handler_name    : VideoHandle
      encoder         : Lavc58.91.100 wrapped_avframe
frame=27476 fps=387 q=-0.0 Lsize=  173252kB time=00:15:24.01 bitrate=1536.0kbits/s speed=  13x
video:14382kB audio:173252kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[Parsed_vfrdet_0 @ 0000023926aeeec0] VFR:0.128662 (3535/23940) min: 2093 max: 11998 avg: 3196

3535/23940
   - Frame Rate: 29
Analyzing audio volume.
tracks: 1
C:\Users\ljose3\Videos\youtube\techntorq\Firefox cookie
['C:\\Users\\ljose3\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\site-packages\\auto_editor\\win-ffmpeg\\bin\\ffprobe.exe', '-v', 'error', '-select_streams', 'v:0', '-show_entries', 'stream=height,width', '-of', 'csv=s=x:p=0', 'VID_20210610_163151.mp4']
1920x1080

t variable: 0
Auto-Editor made 173 cuts, which would have taken about 1.4 hours if edited manually.
Deleting temp dir

**Comment by WyattBlue** [comment]
Thank for pointing this out @lijovklm.
I will investigate this and make a patch soon.

**Comment by lijovklm** [comment]
Thanks. 
While investigating the xml file,

Below code is of silent portion which I have sped up 150%, and <parameter authoringApp="PremierePro"> comes up but here I am exporting this for Resolve. Not sure if this is something to change as well. Please have a look @WyattBlue 

<clipitem id="clipitem-6">
						<masterclipid>masterclip-2</masterclipid>
						<name>VID_20210610_161008.mp4</name>
						<start>1942</start>
						<end>1969</end>
						<in>1317</in>
						<out>1344</out>
						<file id="file-1"/>
						<filter>
							<effect>
								<name>Time Remap</name>
								<effectid>timeremap</effectid>
								<effectcategory>motion</effectcategory>
								<effecttype>motion</effecttype>
								<mediatype>video</mediatype>
								<parameter authoringApp="PremierePro">
									<parameterid>variablespeed</parameterid>
									<name>variablespeed</name>
									<valuemin>0</valuemin>
									<valuemax>1</valuemax>
									<value>0</value>
								</parameter>
								<parameter authoringApp="PremierePro">
									<parameterid>speed</parameterid>
									<name>speed</name>
									<valuemin>-100000</valuemin>
									<valuemax>100000</valuemax>
									<value>150.0</value>
								</parameter>
								<parameter authoringApp="PremierePro">
									<parameterid>reverse</parameterid>
									<name>reverse</name>
									<value>FALSE</value>
								</parameter>
								<parameter authoringApp="PremierePro">
									<parameterid>frameblending</parameterid>
									<name>frameblending</name>
									<value>FALSE</value>
								</parameter>
							</effect>
						</filter>

**Comment by WyattBlue** [comment]
After some experimenting, I found that DaVinci Resolve 17 doesn't link audio-video clips if it's in the old FCP 7 format, but **does** in the FCPXML format.

So instead `--export_to_resolve` using premiere.py with a mirror modification, it can just use final_cut_pro.py, and that should fix it.

@lijovklm I recommend you try this commit right away bb20da5048382cb3e6140cad3915a3d88ce4f568 to see if there are any problems.

**Comment by lijovklm** [comment]
@WyattBlue when I use pip3 install --upgrade pip
it updated to Auto-Editor version 21w22a.

How can I get this specific commit?

**Comment by WyattBlue** [comment]
@lijovklm First download auto-editor with get.

```
git clone https://github.com/WyattBlue/auto-editor.git
cd auto-editor
```

Then run checkout with either the short or full SHA ID.

```
git checkout bb20da5
```

Then install the local version.

```
python3 setup.py install
```

**Comment by lijovklm** [comment]
Thank you and I could install this version

> HEAD is now at bb20da5 Resolve Xml now links clips correctly
and then I installed using python3 setup.py install

However, it didn't fix the issue for me. I could still see the clips not linked (audio and video of same clip) 
I am on resolve 16 and attaching an older xml from this January which still works for me.

While checking both xmls, it seems there's a <sequence > with details in the older xml while it's just a blank tag in new one. Not sure if this is the cause, but please check that too. @WyattBlue 

[VID_20210129_112432.txt](https://github.com/WyattBlue/auto-editor/files/6653142/VID_20210129_112432.txt)

**Comment by mckayc** [comment]
I just discovered Auto-Editor today. THIS IS AMAZING. I just wanted to report that I am using DaVinci Resolve 18 and when I export as "resolve" linking is broken but when I export as "final-cut-pro" it works flawlessly. Thanks for the comment and thanks for building such an amazing tool!
